---
title: " "
pagetitle: "Kindergarten Readiness"

knit: (function(inputFile, encoding) {
      out_dir <- "html-examples";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})

---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=FALSE}
library(tidyverse)
library(echarts4r)
library(psrcplot)

source("equity-tracker-chart-functions.R")

# Order for various factors
quintile_order <- c("Low", "Low\nMedium", "Medium", "Medium\nHigh", "High")

county_order <- c("King", "Kitsap", "Pierce", "Snohomish", "Region")

efa_order <- c("Race/Ethnicity", "Low Income", "Disability Status", 
               "English Proficiency", "Households with Youth <18", 
               "Households with Older Adults 65+")

focus_attribute_order <- c("POC", "Non-POC", "Low Income", "Non-Low\nIncome", 
                           "With\ndisability", "Without\ndisability",
                           "Limited\nEnglish\nproficiency", "English\nproficient",
                           "Household\nwith youth", "Household\nwithout\nyouth",
                           "Household\nwith older\nadult", "Household\nwithout\nolder adult")
# Load data
load("data/kgreadiness.rda")
chart_data <- data_clean %>%
  mutate(focus_attribute_ord = str_wrap(focus_attribute_ord, 12)) %>%
  mutate(focus_attribute_ord = factor(focus_attribute_ord, levels = focus_attribute_order)) %>%
  mutate(data_year = as.character(data_year)) %>%
  distinct() %>%
  arrange(county_ord, focus_type_ord, focus_attribute_ord, data_year)
rm(data_clean)

# Create Facet Line Chart
chart <- equity_tracker_line_facet(df = chart_data,
                                   geo = "county_ord",
                                   x = "data_year",
                                   y = "fact_value",
                                   fill = "focus_attribute_ord",
                                   facet = "focus_type_ord",
                                   title = "Kindergarten Readiness",
                                   y_min = 0,
                                   y_max = NULL,
                                   dec = 0,
                                   esttype = "percent",
                                   color = psrc_colors$blues_inc,
                                   width = '420px',
                                   height = '380px')

```
<p style="font-family: Poppins; font-size:14pt; font-weight:bold">
Kindergarten Readiness by Year
</p>
<p style="font-family: Poppins; font-size:12pt; font-weight:normal">
Calculated using the share of the population age 6+ with ...
</p>
```{r chart, echo=FALSE}
chart
```
<p style="font-family: Poppins; font-size:10pt; font-style:italic">
Source: Washington Office of Superindendent of Public Instruction
</p> 
