---
title: " "
pagetitle: "Kindergarten Readiness"

knit: (function(inputFile, encoding) {
      out_dir <- "html-examples";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})

---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=FALSE}
library(tidyverse)
library(echarts4r)

source("equity-tracker-chart-functions.R")

# Order for various factors
quintile_order <- c("Low", "Low\nMedium", "Medium", "Medium\nHigh", "High")

county_order <- c("King", "Kitsap", "Pierce", "Snohomish", "Region")

efa_order <- c("Race/Ethnicity", "Low Income", "Disability Status", 
               "English Proficiency", "Households with Youth <18", 
               "Households with Older Adults 65+")

focus_attribute_order <- c("POC", "Non-POC", "Low Income", "Non-Low\nIncome", 
                           "With\ndisability", "Without\ndisability",
                           "Limited\nEnglish\nproficiency", "English\nproficient",
                           "Household\nwith youth", "Household\nwithout\nyouth",
                           "Household\nwith older\nadult", "Household\nwithout\nolder adult")

# Load data
load("data/kgreadiness.rda")
chart_data <- data_clean %>%
  mutate(focus_attribute_ord = str_wrap(focus_attribute_ord, 12)) %>%
  mutate(focus_attribute_ord = factor(focus_attribute_ord, levels = focus_attribute_order)) %>%
  distinct() %>%
  arrange(county_ord, focus_type_ord, focus_attribute_ord, data_year)
rm(data_clean)

# Create Facet Line Chart

df = chart_data
geo = "county_ord"
x = "data_year"
y = "fact_value"
facet = "focus_type_ord"
i = 1
color = "blues"
title = "Kindergarten Readiness"
y_min = 0
y_max = NULL
dec = 0
esttype = "percent"
width = '420px'
height = '380px'

max_data <- df %>% dplyr::select(tidyselect::all_of(y)) %>% dplyr::pull() %>% max()
facet_values <- df %>% dplyr::select(tidyselect::all_of(facet)) %>% dplyr::pull() %>% unique
num_facets <- df %>% dplyr::select(tidyselect::all_of(facet)) %>% dplyr::distinct() %>% dplyr::pull() %>% length()

c <- df %>%
  dplyr::mutate(data_year = as.character(.data$data_year)) %>%
  dplyr::filter(.data[[facet]] == facet_values[[i]]) %>%
  dplyr::group_by(.data[[geo]]) %>%
  echarts4r::e_charts_(x, timeline = TRUE, elementId = paste0("chart",i), width = width, height = height) %>% 
  echarts4r::e_line_(y, smooth = FALSE) %>%
  echarts4r::e_color(color) %>%
  echarts4r::e_legend(show = TRUE) %>%
  echarts4r::e_tooltip()


```
<p style="font-family: Poppins; font-size:14pt; font-weight:bold">
Kindergarten Readiness 
</p>
<p style="font-family: Poppins; font-size:12pt; font-weight:normal">
Calculated using the share of the population age 6+ with ...
</p>
```{r chart, echo=FALSE}
c
```
<p style="font-family: Poppins; font-size:10pt; font-style:italic">
Source: Washington Office of Superindendent of Public Instruction
</p> 
