---
title: " "
pagetitle: "Median Household Income"

knit: (function(inputFile, encoding) {
      out_dir <- "html-examples";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})

---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=FALSE}
library(tidyverse)
library(echarts4r)
library(psrcplot)

source("equity-tracker-chart-functions.R")

# Order for various factors
quintile_order <- c("Low", "Low\nMedium", "Medium", "Medium\nHigh", "High")

county_order <- c("Region", "King", "Kitsap", "Pierce", "Snohomish")

efa_order <- c("People of Color", 
               "Households with Lower Income", 
               "People with a Disability", 
               "People with Limited English Proficiency", 
               "Households with Youth <18", 
               "Households with Older Adults 65+")

focus_attribute_order <- c("People of color", 
                           "White\nnon-Hispanic", 
                           "Households with\nlower income", 
                           "With a\ndisability", 
                           "Without a\ndisability",
                           "Limited English\nproficiency", 
                           "English\nproficient",
                           "Households with\nyouth", 
                           "Households with\nolder adults",
                           "Other\nhouseholds")

# Load data
load("data/medincome.rda")
chart_data <- data_clean %>%
  # echarts wants axis to be factors/characters so convert year to a character
  mutate(data_year = as.character(data_year)) %>%
  # Update County Order
  mutate(county_ord = factor(county_ord, levels=county_order)) %>%
  # Update the Equity Focus Area Descriptions
  mutate(focus_type_ord = case_when(
    focus_type=="POC_cat"~"People of Color",
    focus_type=="Disability_cat"~"People with a Disability",
    focus_type=="LEP_cat"~"People with Limited English Proficiency",
    focus_type=="Income_cat"~"Households with Lower Income",
    focus_type=="Youth_cat"~"Households with Youth <18",
    focus_type=="Older_cat"~"Households with Older Adults 65+")) %>%
  mutate(focus_type_ord = factor(focus_type_ord, levels = efa_order)) %>%
  # Update the With/Without Descriptions
  mutate(focus_attribute_ord = case_when(
    focus_attribute== "POC"~ "People of color",
    focus_attribute== "Non-POC"~ "White non-Hispanic",
    focus_attribute== "Low Income"~ "Households with lower income",
    focus_attribute== "Non-Low Income"~ "Other households",
    focus_attribute== "With disability"~ "With a disability",
    focus_attribute== "Without disability"~ "Without a disability",
    focus_attribute== "Limited English proficiency"~ "Limited English proficiency",
    focus_attribute== "English proficient"~ "English proficient",
    focus_attribute== "Household with youth"~ "Households with youth",
    focus_attribute== "Household without youth"~ "Other households",
    focus_attribute== "Household with older adult"~ "Households with older adults",
    focus_attribute== "Household without older adult"~ "Other households")) %>%
  mutate(focus_attribute_ord = str_wrap(focus_attribute_ord, 15)) %>%
  mutate(focus_attribute_ord = factor(focus_attribute_ord, levels = focus_attribute_order)) %>%
  # Remove any duplicates
  distinct() %>%
  # Sort the data to ensure the charts work
  arrange(county_ord, focus_type_ord, focus_attribute_ord, data_year)
rm(data_clean)

# Create Facet Line Chart
chart <- equity_tracker_line_facet(df = chart_data,
                                   geo = "county_ord",
                                   x = "data_year",
                                   y = "fact_value",
                                   fill = "focus_attribute_ord",
                                   facet = "focus_type_ord",
                                   title = "Median Household Income",
                                   y_min = 0,
                                   y_max = 180000,
                                   dec = 0,
                                   esttype = "currency",
                                   color = psrc_colors$purples_inc,
                                   width = '420px',
                                   height = '380px')

```
<p style="font-family: Poppins; font-size:14pt; font-weight:bold">
Median Household Income
</p>
<p style="font-family: Poppins; font-size:12pt; font-weight:normal">
American Community Survey Population data from 2017-2021 
</p>
```{r chart, echo=FALSE}
chart
```
<p style="font-family: Poppins; font-size:10pt; font-style:italic">
Source: US Census Bureau American Community Survey Public Use Microdata Sample
</p> 
