---
title: " "
pagetitle: "Median Household Income"

knit: (function(inputFile, encoding) {
      out_dir <- "html-examples";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})

---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=FALSE}
library(tidyverse)
library(echarts4r)

source("equity-tracker-chart-functions.R")

# Order for various factors
quintile_order <- c("Low", "Low\nMedium", "Medium", "Medium\nHigh", "High")

county_order <- c("King", "Kitsap", "Pierce", "Snohomish", "Region")

efa_order <- c("Race/Ethnicity", "Low Income", "Disability Status", 
               "English Proficiency", "Households with Youth <18", 
               "Households with Older Adults 65+")

focus_attribute_order <- c("POC", "Non-POC", "Low Income", "Non-Low\nIncome", 
                           "With\ndisability", "Without\ndisability",
                           "Limited\nEnglish\nproficiency", "English\nproficient",
                           "Household\nwith youth", "Household\nwithout\nyouth",
                           "Household\nwith older\nadult", "Household\nwithout\nolder adult")

# Load data
load("data/medincome.rda")
chart_data <- data_clean %>%
  mutate(focus_attribute_ord = str_wrap(focus_attribute_ord, 12)) %>%
  mutate(focus_attribute_ord = factor(focus_attribute_ord, levels = focus_attribute_order)) %>%
  arrange(county_ord, focus_type_ord, focus_attribute_ord)
rm(data_clean)

# Create Facet Column Chart
chart <- equity_tracker_column_facet(df = chart_data,
                                     geo = "county_ord",
                                     x = "focus_attribute_ord",
                                     y = "fact_value",
                                     facet = "focus_type_ord",
                                     title = "Median Household Income",
                                     y_min = 0,
                                     y_max = 180000,
                                     dec = 0,
                                     esttype = "currency",
                                     color = "purples")

```
<p style="font-family: Poppins; font-size:14pt; font-weight:bold">
Median Household Income  
</p>
<p style="font-family: Poppins; font-size:12pt; font-weight:normal">
American Community Survey Population data from 2017-2021  
</p>
```{r chart, echo=FALSE}
chart
```
<p style="font-family: Poppins; font-size:10pt; font-style:italic">
Source: US Census Bureau American Community Survey Public Use Microdata Sample
</p> 
