---
title: " "
pagetitle: "Traffic Related Deaths"

knit: (function(inputFile, encoding) {
      out_dir <- "html-examples";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})

---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=FALSE}
library(tidyverse)
library(echarts4r)
library(psrcplot)

source("equity-tracker-chart-functions.R")

# Order for various factors
quintile_order <- c("Low", "Low\nMedium", "Medium", "Medium\nHigh", "High")

county_order <- c("Region", "King", "Kitsap", "Pierce", "Snohomish")

efa_order <- c("People of Color", 
               "Households with Lower Income", 
               "People with a Disability", 
               "People with Limited English Proficiency", 
               "Households with Youth <18", 
               "Households with Older Adults 65+")

focus_attribute_order <- c("People of\ncolor", 
                           "White\nnon-Hispanic", 
                           "Households\nwith lower\nincome", 
                           "With a\ndisability", 
                           "Without a\ndisability",
                           "Limited\nEnglish\nproficiency", 
                           "English\nproficient",
                           "Households\nwith youth", 
                           "Households\nwith older\nadults",
                           "Other\nhouseholds")
# Load data
chart_data <- NULL
for (yrs in seq(2016,2022,by=1)) {
  
  load(paste0("data/safety_",yrs,".rda"))
  temp <- safety_quintile_data %>%
  # echarts wants axis to be factors/characters so convert year to a character
  mutate(data_year = as.character(data_year)) %>%
  # Update County Order
  mutate(county_ord = factor(county, levels=county_order)) %>%
  # Update the Equity Focus Area Descriptions
  mutate(equity_group_ord = case_when(
    equity_group_ord=="Race/Ethnicity"~"People of Color",
    equity_group_ord=="Disability Status"~"People with a Disability",
    equity_group_ord=="English Proficiency"~"People with Limited English Proficiency",
    equity_group_ord=="Low Income"~"Households with Lower Income",
    equity_group_ord=="Households with Youth <18"~"Households with Youth <18",
    equity_group_ord=="Households with Older Adults 65+"~"Households with Older Adults 65+")) %>%
  mutate(equity_group_ord = factor(equity_group_ord, levels = efa_order)) %>%
  # Remove any duplicates
  distinct() %>% 
  arrange(county_ord, equity_group_ord, quintile, data_year)
  
  rm(safety_quintile_data)
  ifelse(is.null(chart_data), chart_data <- temp, chart_data <- bind_rows(chart_data, temp))
  
}

# Create Facet Line Chart
chart <- equity_tracker_line_facet(df = chart_data,
                                   geo = "county_ord",
                                   x = "data_year",
                                   y = "Deaths per 100k people",
                                   fill = "quintile",
                                   facet = "equity_group_ord",
                                   title = "Traffic Related Deaths per 100k people",
                                   y_min = 0,
                                   y_max = NULL,
                                   dec = 0,
                                   esttype = "number",
                                   color = psrc_colors$pognbgy_5,
                                   width = '420px',
                                   height = '380px')

```
<p style="font-family: Poppins; font-size:14pt; font-weight:bold">
Traffic Related Deaths per 100,000 people  
</p>
<p style="font-family: Poppins; font-size:12pt; font-weight:normal">
Five-Year Average of Traffic Related Deaths from 2018-2022
</p>
```{r chart, echo=FALSE}
chart
```
<p style="font-family: Poppins; font-size:10pt; font-style:italic">
Source: Washington State Traffic Safety Commission Coded Data File
</p> 
